apiVersion: v1
kind: Service
metadata:
    name: gru-web-lb
spec:
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
    selector:
        name: gru-web
    type: LoadBalancer
