apiVersion: v1
kind: Service
metadata:
  labels:
    app: gru-cms
  name: gru-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: gru-cms
  type: NodePort
