apiVersion: v1
kind: Service
metadata:
    name: gru-service
spec:
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
    selector:
        name: gru-cms
    type: LoadBalancer
